iter1
Vova4o/final-project-10th-sprint pull request #1
Opened 2024-03-08 06:53 UTC by Vova4o

Я не смог проверит все дословно, почему-то в терминале в nano не могу писать по русски...

2024-03-08 10:00 UTC, dirtymew requested changes
Привет Владимир

Отличная работа - скрипт работает.

Есть маленькая ошибка - которую полезно поправить.

По поводу редактирования скриптов в nano - это полезно уметь так как зачастую на серверах и контейнрах нет редакторов - да и nano не всегда. Но для разработки лучше пользоватся IDE там и плагины для bash есть.. Если под windows то можно в WSL отлаживать или поставить виртуальную машину с linux и настроить IDE на работу под ssh - ну или все в docker-е... 


https://code.visualstudio.com/docs/remote/ssh
https://code.visualstudio.com/docs/remote/wsl
https://stackoverflow.com/questions/12293494/how-to-develop-in-linux-like-shell-bash-on-windows

2024-03-08 10:00 UTC, dirtymew commented on precode.sh
> +chmod 764 dir2/hello.sh
тут нужно только добавить execute - можно проще chmod +x

2024-03-08 10:00 UTC, dirtymew commented on precode.sh
> +dir2/hello.sh $NAME >> dir1/summary.txt
неверный выводу у скрипта

выводиться  "Всем привет" а хотелось "Всем студентам привет"

попробуй разобраться почему

2024-03-09 03:08 UTC, Vova4o commented on precode.sh
> +dir2/hello.sh $NAME >> dir1/summary.txt
Разобрался, почему но понял не до конца. В общем передавалось только одно значение, а чтобы передать всю строку надо было заключить ее в кавычки.

2024-03-09 03:08 UTC, Vova4o commented on precode.sh
> +chmod 764 dir2/hello.sh
Я пытался разобраться, но получатся что права должны быть rwxrw-r-- что по идее соответствует 764
Если поставить +x то это добавит прав на выполнение файла?

2024-03-09 11:36 UTC, dirtymew commented on precode.sh
> +chmod 764 dir2/hello.sh
да

2024-03-09 11:37 UTC, dirtymew commented on precode.sh
> +dir2/hello.sh $NAME >> dir1/summary.txt
передавалось все но без скобок каждое "слово" было отдельным аргументом - так как скрипт работал только с первым так и получалось

2024-03-09 11:38 UTC, dirtymew approved these changes
Привет Владимир

Отлично - все исправлено - зачет.

2024-03-11 11:07 UTC, merged